import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"
import Logo from "./components/Logo"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "virts.dev",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-slate-100 to-slate-300">
        <nav
          className="flex container mx-auto items-center justify-between p-6 lg:px-8"
          aria-label="Global"
        >
          <div className="flex lg:flex-1">
            <a
              href="/"
              className="-m-1.5 p-1.5 flex justify-center items-center"
            >
              <Logo /> <h1 className="font-bold text-4xl ml-3">Andrew Virts</h1>
            </a>
          </div>
          <div className="flex lg:hidden">
            <button
              type="button"
              className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
            >
              <span className="sr-only">Open main menu</span>
              <svg
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                aria-hidden="true"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                />
              </svg>
            </button>
          </div>
          <div className="hidden lg:flex lg:gap-x-12">
            <Link
              className="text-sm font-semibold leading-6 text-gray-900"
              href="/"
            >
              Home
            </Link>
            <Link
              className="text-sm font-semibold leading-6 text-gray-900"
              href="/about"
            >
              About
            </Link>
            <Link
              className="text-sm font-semibold leading-6 text-gray-900"
              href="/portfolio"
            >
              Portfolio
            </Link>
            <Link
              className="text-sm font-semibold leading-6 text-gray-900"
              href="/blog"
            >
              Blog
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
